---
title: "Aula 06 - RMarkdown"
author: "Regis Spindola"
date: "28/06/2018"
output: html_document
---

##Distribuição Normal e K-means##
* Usar a distribuição normal para gerar uma variação nos dados gerados
  * Sugestão:
    * População com 15 observações 
    * 3 centróides
    * 5 observações por centróide
* Essa população deve ser impressa (plot) no plano cartesiano

```{r}
set.seed(1909)
x <- rnorm(15, mean = rep(1:3, each = 5), sd = 0.2)
y <- rnorm(15, mean = rep(c(1,2), each = 5), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 1)
text(x + 0.05, y + 0.05, labels = as.character(1:15))
```

```{r}
df <- data.frame(x, y)
nclusters <- 3
modelo.kmean <- kmeans(x = df, centers = nclusters)
plot(x, y, col = modelo.kmean$cluster, pch = 19, cex = 2)
points(modelo.kmean$centers, col = 1:nclusters, pch = 3, cex = 3, lwd = 2)
```

##Importando o DataSet Fifa##
```{r}
fifa_game_2 <- read.csv('~/Downloads/fifa game-2.csv')
```


```{r}
fifa_game_2 %>%
  filter(league == "Spanish Primera División") %>%
  select(name, dribbling, acceleration) -> liga_spanish

```



```{r}

```


```{r}
set.seed(12345)
dados <- matrix(rnorm(400), nrow = 40)
image(x = 1:10, y = 1:40, z = t(dados)[,40:1])
```

